- name: Check if target ruby is installed
  shell: cd; bash -lc "rbenv versions | grep {{ ruby_version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '"
  register: ruby_is_installed

- name: Install ruby
  shell: cd; bash -lc "MAKEOPTS={{ ruby_makeopts }} CONFIGURE_OPTS=--disable-install-rdoc rbenv install {{ ruby_version }}"
  when: ruby_is_installed.stdout != ruby_version

- name: Set global ruby version
  when: ruby_is_installed.stdout != ruby_version
  shell: cd; bash -lc "rbenv global {{ ruby_version }}"
